CREATE TABLE IF NOT EXISTS Colors (
	ID BIGINT PRIMARY KEY,
	Name VARCHAR (200) NOT NULL
);

CREATE TABLE IF NOT EXISTS SouvenirsCategories (
	ID BIGINT PRIMARY KEY,
	IdParent BIGINT REFERENCES SouvenirsCategories(ID),
	Name VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS SouvenirMaterials (
	ID INT PRIMARY KEY,
	Name VARCHAR (200) NOT NULL
);

CREATE TABLE IF NOT EXISTS ApplicationMetods (
	ID INT PRIMARY KEY,
	Name VARCHAR (200) NOT NULL
);

CREATE TABLE IF NOT EXISTS Providers (
	ID BIGINT PRIMARY KEY,
	Name VARCHAR (200) NOT NULL,
	Email VARCHAR (200) NOT NULL,
	ContactPerson VARCHAR (200) NOT NULL,
	Comments VARCHAR (200)
);

CREATE TABLE IF NOT EXISTS ProcurementStatuses (
	ID BIGINT PRIMARY KEY,
	Name VARCHAR (200) NOT NULL
);

CREATE TABLE IF NOT EXISTS SouvenirProcurements (
	ID BIGINT PRIMARY KEY,
	IdProvider BIGINT NOT NULL REFERENCES Providers(ID),
	Data DATE NOT NULL,
	IdStatus BIGINT NOT NULL REFERENCES ProcurementStatuses(ID)
);

CREATE TABLE IF NOT EXISTS Souvenirs (
	ID BIGINT PRIMARY KEY,
	URL VARCHAR (100) NOT NULL,
	ShortName VARCHAR (150) NOT NULL,
	Name VARCHAR (200) NOT NULL,
	Description VARCHAR (2500) NOT NULL,
	Rating SMALLINT NOT NULL,
	IdCategory BIGINT NOT NULL REFERENCES SouvenirsCategories(ID),
	IdColor BIGINT NOT NULL REFERENCES Colors(ID),
	Size VARCHAR (150) NOT NULL,
	IdMaterial INT NOT NULL REFERENCES SouvenirMaterials(ID),
	Weight DECIMAL (10, 3),
	QTypics VARCHAR (10),
	PicsSize VARCHAR (20),
	IdApplicMetod INT NOT NULL REFERENCES ApplicationMetods(ID),
	AllCategories VARCHAR (150) NOT NULL,
	DealerPrice DECIMAL (10, 2) NOT NULL,
	Price DECIMAL (10, 2) NOT NULL,
	Comments VARCHAR (1000)
);

CREATE TABLE IF NOT EXISTS ProcurementSouvenirs (
	ID BIGINT PRIMARY KEY,
	IdSouvenir BIGINT NOT NULL REFERENCES Souvenirs(ID),
	IdProcurement BIGINT NOT NULL REFERENCES SouvenirProcurements(ID),
	Amount BIGINT NOT NULL,
	Price DECIMAL (10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS SouvenirStores (
	ID BIGINT PRIMARY KEY,
	IdSouvenir BIGINT NOT NULL REFERENCES Souvenirs(ID),
	IdProcurement BIGINT NOT NULL REFERENCES SouvenirProcurements(ID),
	Amount BIGINT NOT NULL,
	Comments VARCHAR (200)
);

